"use client";

import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { showSuccess, showError } from '@/utils/toast';
import { supabase } from '@/integrations/supabase/client';
import { Loader2, DollarSign, CheckCircle2 } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';

interface PartialPaymentModalProps {
  isOpen: boolean;
  onClose: () => void;
  bill: any;
  tenantId: string;
  onSuccess: () => void;
}

export const PartialPaymentModal = ({ isOpen, onClose, bill, tenantId, onSuccess }: PartialPaymentModalProps) => {
  const [loading, setLoading] = useState(false);
  const [paidValue, setPaidValue] = useState('');
  const queryClient = useQueryClient();

  useEffect(() => {
    if (isOpen && bill) {
      setPaidValue('');
    }
  }, [isOpen, bill]);

  const handleConfirm = async (e: React.FormEvent) => {
    e.preventDefault();
    const amountToPay = parseFloat(paidValue);
    const originalValue = Number(bill?.total_value || bill?.calculated_value || 0);

    if (isNaN(amountToPay) || amountToPay <= 0) {
      showError("Insira um valor válido maior que zero.");
      return;
    }

    if (amountToPay > originalValue) {
      showError(`O valor pago não pode ser maior que o valor da fatura (R$ ${originalValue.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}).`);
      return;
    }

    setLoading(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Não autenticado');

      const remainingValue = originalValue - amountToPay;
      const billYear = typeof bill.year === 'string' ? parseInt(bill.year) : (Number(bill.year) || new Date().getFullYear());
      const billMonth = bill.month ? bill.month.toString().padStart(2, '0') : (new Date().getMonth() + 1).toString().padStart(2, '0');

      if (remainingValue === 0) {
        // Se pagou o valor total, apenas dá baixa normal
        if (bill.isAutoGenerated) {
          const { error } = await supabase.from('bills').insert([{
            user_id: user.id,
            tenant_id: tenantId || null,
            property_id: bill.property_id || null,
            type: bill.type,
            month: billMonth,
            year: billYear,
            total_value: originalValue,
            calculated_value: originalValue,
            status: 'pago',
            payment_date: new Date().toISOString(),
            description: bill.description || 'Pagamento Integral'
          }]);
          if (error) throw error;
        } else {
          const { error } = await supabase.from('bills').update({
            status: 'pago',
            payment_date: new Date().toISOString()
          }).eq('id', bill.id);
          if (error) throw error;
        }
      } else {
        // Pagamento Parcial:
        // 1. Cria o registro do valor PAGO
        const { error: err1 } = await supabase.from('bills').insert([{
          user_id: user.id,
          tenant_id: tenantId || null,
          property_id: bill.property_id || null,
          type: bill.type,
          month: billMonth,
          year: billYear,
          total_value: amountToPay,
          calculated_value: amountToPay,
          status: 'pago',
          payment_date: new Date().toISOString(),
          description: `Pagamento Parcial (Original: R$ ${originalValue.toLocaleString('pt-BR', { minimumFractionDigits: 2 })})`
        }]);
        if (err1) throw err1;

        // 2. Atualiza ou cria o registro do valor RESTANTE (Pendente)
        if (bill.isAutoGenerated) {
          const { error: err2 } = await supabase.from('bills').insert([{
            user_id: user.id,
            tenant_id: tenantId || null,
            property_id: bill.property_id || null,
            type: bill.type,
            month: billMonth,
            year: billYear,
            total_value: remainingValue,
            calculated_value: remainingValue,
            status: 'pendente',
            description: `Saldo restante de pagamento parcial`
          }]);
          if (err2) throw err2;
        } else {
          const { error: err3 } = await supabase.from('bills').update({
            total_value: remainingValue,
            calculated_value: remainingValue,
            description: `Saldo restante (Original: R$ ${originalValue.toLocaleString('pt-BR', { minimumFractionDigits: 2 })})`
          }).eq('id', bill.id);
          if (err3) throw err3;
        }
      }

      showSuccess(`Pagamento parcial de R$ ${amountToPay.toLocaleString('pt-BR', { minimumFractionDigits: 2 })} registrado!`);
      
      // Invalida os caches para atualizar a tela instantaneamente
      queryClient.invalidateQueries({ queryKey: ['bills'] });
      queryClient.invalidateQueries({ queryKey: ['tenant-financial-v6', tenantId] });
      queryClient.invalidateQueries({ queryKey: ['tenant', tenantId] });
      queryClient.invalidateQueries({ queryKey: ['dashboard-stats-v6'] });
      queryClient.invalidateQueries({ queryKey: ['tenants-dashboard-active'] });

      onSuccess();
      onClose();
    } catch (err: any) {
      showError("Erro ao processar pagamento parcial: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[400px] rounded-[2.5rem] p-8">
        <DialogHeader>
          <DialogTitle className="text-2xl font-black tracking-tight">Pagamento Parcial</DialogTitle>
          <p className="text-sm text-slate-500 font-medium">
            Registre um pagamento parcial para a fatura de <span className="font-bold text-slate-900">{bill?.type} ({bill?.month}/{bill?.year})</span>.
          </p>
        </DialogHeader>

        <form onSubmit={handleConfirm} className="space-y-6 pt-4">
          <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100 flex justify-between items-center">
            <span className="text-xs font-bold text-slate-400 uppercase">Valor Total Atual</span>
            <span className="font-black text-slate-900 text-base">
              R$ {Number(bill?.total_value || bill?.calculated_value || 0).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}
            </span>
          </div>

          <div className="space-y-2">
            <Label className="text-[10px] font-black text-blue-600 uppercase tracking-widest ml-1">Valor Sendo Pago Agora (R$)</Label>
            <div className="relative">
              <DollarSign className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-blue-500" />
              <Input 
                type="number" 
                step="0.01"
                placeholder="0,00" 
                value={paidValue}
                onChange={e => setPaidValue(e.target.value)}
                className="h-14 pl-12 rounded-2xl bg-blue-50/30 border-none font-black text-xl text-blue-900 focus-visible:ring-2 focus-visible:ring-blue-500/20"
                required
                autoFocus
              />
            </div>
            {paidValue && !isNaN(parseFloat(paidValue)) && (
              <p className="text-[10px] text-slate-400 font-bold uppercase mt-2 ml-1">
                Saldo Restante Pendente: R$ {Math.max(0, Number(bill?.total_value || bill?.calculated_value || 0) - parseFloat(paidValue)).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}
              </p>
            )}
          </div>

          <DialogFooter className="gap-3">
            <Button type="button" variant="ghost" onClick={onClose} className="rounded-xl font-bold text-slate-400">Cancelar</Button>
            <Button 
              type="submit"
              disabled={loading || !paidValue}
              className="bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl px-8 font-black h-12 shadow-lg shadow-emerald-100 flex-1"
            >
              {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <CheckCircle2 className="w-5 h-5" />}
              Confirmar Parcela
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};