// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yavflkviynasysecxyvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdmZsa3ZpeW5hc3lzZWN4eXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxNzM0ODYsImV4cCI6MjA5Mzc0OTQ4Nn0.SoYFMTOEWfDzH6oKAWX1uYJJZP1i-vqpDeExdc5gl0U";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);